### ISSUE TITLE
Isolate Bloc v2

### ISSUE THREAD

**Issue by Maksimka101** [Maksimka101/isolate-bloc#11]
Hello everyone!

I have started moving this package to the flutter 2 & null-safety so this is a place for discussions

I have a big plans and hope they become real!

# Roadmap

- [ ] Move to null-safety & flutter 2
- [ ] Update api to keep up with Felix's bloc
- [ ] Update documentation
- [ ] Write unit tests
- [ ] Write integration tests
- [ ] Write performance tests for:
    - initialization
    - bloc creating
- [ ] Make extensible api

**Comment by Maksimka101** [comment]
@squallsama Yes, I thought. The implementation of the `on` api will greatly change the api of the entire library, so I want to try it first in the implementation of the felix's bloc
